/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silo;

import java.text.ParseException;

/**
 *
 * @author putrinatih
 */
public class DeliveryNoteForm extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryNoteForm
     */
    public DeliveryNoteForm() {
        initComponents();
        
        confirmationMessage = new ConfirmationMessage(this);
        confirmationMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        invoiceNumberLabel = new javax.swing.JLabel();
        deliveryNoteNumLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        orderDateLabel = new javax.swing.JLabel();
        deliveryDateLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        invoiceNumberTF = new javax.swing.JTextField();
        deliveryNoteNumberTF = new javax.swing.JTextField();
        customerNameTF = new javax.swing.JTextField();
        orderDateTF = new javax.swing.JTextField();
        deliveryDateTF = new javax.swing.JTextField();
        statusTF = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        invoiceNumberLabel.setText("Invoice Number");

        deliveryNoteNumLabel.setText("Delivery Note Number");

        customerNameLabel.setText("Customer Name");

        orderDateLabel.setText("Order Date");

        deliveryDateLabel.setText("Delivery Date");

        statusLabel.setText("Status ");

        invoiceNumberTF.setBackground(new java.awt.Color(255, 204, 153));

        deliveryNoteNumberTF.setBackground(new java.awt.Color(255, 204, 153));

        customerNameTF.setBackground(new java.awt.Color(255, 204, 153));

        orderDateTF.setBackground(new java.awt.Color(255, 204, 153));

        deliveryDateTF.setBackground(new java.awt.Color(255, 204, 153));

        statusTF.setBackground(new java.awt.Color(255, 204, 153));

        createButton.setBackground(new java.awt.Color(255, 153, 51));
        createButton.setText("Create");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        jLabel8.setText("SISTEM INFORMASI LOGISTIK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(invoiceNumberLabel)
                    .addComponent(deliveryNoteNumLabel)
                    .addComponent(customerNameLabel)
                    .addComponent(orderDateLabel)
                    .addComponent(deliveryDateLabel)
                    .addComponent(statusLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(invoiceNumberTF)
                    .addComponent(deliveryNoteNumberTF)
                    .addComponent(customerNameTF)
                    .addComponent(orderDateTF)
                    .addComponent(deliveryDateTF)
                    .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceNumberLabel)
                    .addComponent(invoiceNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryNoteNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliveryNoteNumLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderDateLabel)
                    .addComponent(orderDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryDateLabel)
                    .addComponent(deliveryDateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked

        confirmationMessage.setVisible(true);
    }//GEN-LAST:event_createButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    
    public void confirm() throws ParseException{
        confirmationMessage.setVisible(false);
        deliveryNoteCtl.addNewDeliveryNoteData(invoiceNumberTF.getText(), deliveryNoteNumberTF.getText(), customerNameTF.getText(),
                orderDateTF.getText(), deliveryDateTF.getText(), statusTF.getText());
        
        invoiceNumberTF.setText("");
        deliveryNoteNumberTF.setText("");
        customerNameTF.setText("");
        orderDateTF.setText("");
        deliveryDateTF.setText("");
        statusTF.setText("");
    }

    public void setController(DeliveryNoteCtl deliveryNoteCtl){
        this.deliveryNoteCtl = deliveryNoteCtl;
    }
    
    ConfirmationMessage confirmationMessage;
    DeliveryNoteCtl deliveryNoteCtl;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTF;
    private javax.swing.JLabel deliveryDateLabel;
    private javax.swing.JTextField deliveryDateTF;
    private javax.swing.JLabel deliveryNoteNumLabel;
    private javax.swing.JTextField deliveryNoteNumberTF;
    private javax.swing.JLabel invoiceNumberLabel;
    private javax.swing.JTextField invoiceNumberTF;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel orderDateLabel;
    private javax.swing.JTextField orderDateTF;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTF;
    // End of variables declaration//GEN-END:variables
}
