/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package silo;

import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    static DBHandler dbHandler;
    static DeliveryNoteDetailPage deliveryNoteDetailPage;
    static ItemForm editItemForm;
    static InvoiceDetailPage invoiceDetailPage;
    static DaftarInvoiceCtl listInvoiceCtl;
    static InvoiceCtl invoiceCtl;
    static ItemForm addNewItemForm;
    static DeliveryNoteForm deliveryNoteForm;
    static DeliveryNoteCtl deliveryNoteCtl;
    static DaftarDeliveryNoteCtl listDeliveryNoteCtl;
    static DaftarItemCtl listItemCtl;
    static ItemCtl itemCtl;
    static DialogBox dialogBox;
   
    
    
    public MainPage() throws ParseException {
        
        initComponents();
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        
        dbHandler = new DBHandler();
        
        
        deliveryNoteDetailPage = new DeliveryNoteDetailPage();
        deliveryNoteForm = new DeliveryNoteForm();
        addNewItemForm = new ItemForm(1);
        editItemForm = new ItemForm(2);
        invoiceDetailPage = new InvoiceDetailPage();
        dialogBox = new DialogBox(addNewItemForm);
        
        deliveryNoteCtl = new DeliveryNoteCtl(dbHandler,this,deliveryNoteForm, deliveryNoteDetailPage);
        listDeliveryNoteCtl = new DaftarDeliveryNoteCtl(dbHandler,this);
        itemCtl = new ItemCtl(dbHandler,this,addNewItemForm, editItemForm);
        listItemCtl = new DaftarItemCtl(dbHandler,this);
        listInvoiceCtl = new DaftarInvoiceCtl(dbHandler,this);
        invoiceCtl = new InvoiceCtl(dbHandler, this, invoiceDetailPage);
        
        addNewItemForm.setController(itemCtl, dialogBox);
        editItemForm.setController(itemCtl, dialogBox);
        deliveryNoteForm.setController(deliveryNoteCtl);
        deliveryNoteDetailPage.setController(deliveryNoteCtl);
        invoiceDetailPage.setController(invoiceCtl);
        
        deliveryNoteDetailPage.setVisible(false);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        searchItemTF = new javax.swing.JTextField();
        searchItemBtn = new javax.swing.JButton();
        btnHolder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listInvoice = new javax.swing.JTable();
        searchInvoiceTF = new javax.swing.JTextField();
        searchInvoiceBtn = new javax.swing.JButton();
        invoiceViewBtnHolder = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listDeliveryNote = new javax.swing.JTable();
        searchDeliveryNoteTF = new javax.swing.JTextField();
        searchDeliveyNoteBtn = new javax.swing.JButton();
        viewDeliveryNoteBtn = new javax.swing.JButton();
        dnEditBtnHolder = new javax.swing.JPanel();
        menuMB = new javax.swing.JMenuBar();
        itemMI = new javax.swing.JMenu();
        invoiceMI = new javax.swing.JMenu();
        deliveryNotesMI = new javax.swing.JMenu();
        createDeliveryNoteMenu = new javax.swing.JMenu();
        viewDeliveryNoteMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        listItem.setBackground(new java.awt.Color(255, 153, 153));
        listItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Title", "Manufacturer", "number of stocks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listItem);

        addBtn.setBackground(new java.awt.Color(255, 153, 153));
        addBtn.setText("Add Item");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        this.addBtn.setVisible(false);

        searchItemTF.setBackground(new java.awt.Color(255, 204, 255));
        searchItemTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemTFActionPerformed(evt);
            }
        });

        searchItemBtn.setBackground(new java.awt.Color(255, 153, 153));
        searchItemBtn.setText("Search Item");
        searchItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchItemBtnMouseClicked(evt);
            }
        });
        searchItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemBtnActionPerformed(evt);
            }
        });

        btnHolder.setBackground(new java.awt.Color(255, 204, 204));
        btnHolder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHolderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnHolderLayout = new javax.swing.GroupLayout(btnHolder);
        btnHolder.setLayout(btnHolderLayout);
        btnHolderLayout.setHorizontalGroup(
            btnHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );
        btnHolderLayout.setVerticalGroup(
            btnHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchItemBtn)
                .addGap(18, 18, 18)
                .addComponent(searchItemTF, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(425, Short.MAX_VALUE)
                    .addComponent(btnHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItemBtn)
                    .addComponent(addBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(74, Short.MAX_VALUE)
                    .addComponent(btnHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        listInvoice.setBackground(new java.awt.Color(204, 204, 0));
        listInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Number", "PO Number", "Supplier Name", "Order Date", "Delivery Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(listInvoice);

        searchInvoiceTF.setBackground(new java.awt.Color(255, 255, 204));
        searchInvoiceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInvoiceTFActionPerformed(evt);
            }
        });

        searchInvoiceBtn.setBackground(new java.awt.Color(204, 204, 0));
        searchInvoiceBtn.setText("Search Invoice");
        searchInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInvoiceBtnMouseClicked(evt);
            }
        });

        invoiceViewBtnHolder.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout invoiceViewBtnHolderLayout = new javax.swing.GroupLayout(invoiceViewBtnHolder);
        invoiceViewBtnHolder.setLayout(invoiceViewBtnHolderLayout);
        invoiceViewBtnHolderLayout.setHorizontalGroup(
            invoiceViewBtnHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        invoiceViewBtnHolderLayout.setVerticalGroup(
            invoiceViewBtnHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchInvoiceBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchInvoiceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(424, Short.MAX_VALUE)
                    .addComponent(invoiceViewBtnHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInvoiceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInvoiceBtn))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addComponent(invoiceViewBtnHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        listDeliveryNote.setBackground(new java.awt.Color(0, 153, 153));
        listDeliveryNote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Number", "Delivery Note Number", "Customer Name", "Order Date", "Delivery Date", "Status"
            }
        ));
        jScrollPane3.setViewportView(listDeliveryNote);

        searchDeliveryNoteTF.setBackground(new java.awt.Color(204, 255, 255));
        searchDeliveryNoteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDeliveryNoteTFActionPerformed(evt);
            }
        });

        searchDeliveyNoteBtn.setBackground(new java.awt.Color(0, 153, 153));
        searchDeliveyNoteBtn.setText("Search Delivery Note");
        searchDeliveyNoteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchDeliveyNoteBtnMouseClicked(evt);
            }
        });

        viewDeliveryNoteBtn.setBackground(new java.awt.Color(0, 153, 153));
        viewDeliveryNoteBtn.setText("View");

        dnEditBtnHolder.setBackground(new java.awt.Color(0, 153, 153));
        dnEditBtnHolder.setForeground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout dnEditBtnHolderLayout = new javax.swing.GroupLayout(dnEditBtnHolder);
        dnEditBtnHolder.setLayout(dnEditBtnHolderLayout);
        dnEditBtnHolderLayout.setHorizontalGroup(
            dnEditBtnHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        dnEditBtnHolderLayout.setVerticalGroup(
            dnEditBtnHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(searchDeliveyNoteBtn)
                        .addGap(18, 18, 18)
                        .addComponent(searchDeliveryNoteTF))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewDeliveryNoteBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(dnEditBtnHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDeliveryNoteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDeliveyNoteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewDeliveryNoteBtn))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(dnEditBtnHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        menuMB.setBackground(new java.awt.Color(204, 204, 255));
        menuMB.setForeground(new java.awt.Color(204, 204, 255));

        itemMI.setText("Item");
        itemMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMIMouseClicked(evt);
            }
        });
        menuMB.add(itemMI);

        invoiceMI.setText("Invoice");
        invoiceMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceMIMouseClicked(evt);
            }
        });
        menuMB.add(invoiceMI);

        deliveryNotesMI.setText("Delivery Notes");

        createDeliveryNoteMenu.setText("Create Delivery Note");
        createDeliveryNoteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createDeliveryNoteMenuMouseClicked(evt);
            }
        });
        deliveryNotesMI.add(createDeliveryNoteMenu);

        viewDeliveryNoteMenu.setText("View Delivery Notes List");
        viewDeliveryNoteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDeliveryNoteMenuMouseClicked(evt);
            }
        });
        deliveryNotesMI.add(viewDeliveryNoteMenu);

        menuMB.add(deliveryNotesMI);

        setJMenuBar(menuMB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMIMouseClicked

        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(true);
        addBtn.setVisible(true);
        listItemCtl.getItemList();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMIMouseClicked

    private void invoiceMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMIMouseClicked
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        listInvoiceCtl.getListInvoice();

        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceMIMouseClicked

    private void createDeliveryNoteMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createDeliveryNoteMenuMouseClicked
        deliveryNoteCtl.requestDeliveryNoteForm();
    }//GEN-LAST:event_createDeliveryNoteMenuMouseClicked

    private void viewDeliveryNoteMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDeliveryNoteMenuMouseClicked
        jPanel2.setVisible(false);
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);

        listDeliveryNoteCtl.getListDeliveryNote();
    }//GEN-LAST:event_viewDeliveryNoteMenuMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        itemCtl.requestNewItemForm();
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchItemTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemTFActionPerformed

    private void searchItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchItemBtnMouseClicked
        listItemCtl.searchItem(searchItemTF.getText());
    }//GEN-LAST:event_searchItemBtnMouseClicked

    private void searchItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemBtnActionPerformed

    private void btnHolderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHolderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHolderMouseClicked

    private void searchInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInvoiceBtnMouseClicked
        listInvoiceCtl.searchInvoice(searchInvoiceTF.getText());
    }//GEN-LAST:event_searchInvoiceBtnMouseClicked

    private void searchDeliveryNoteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDeliveryNoteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDeliveryNoteTFActionPerformed

    private void searchDeliveyNoteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchDeliveyNoteBtnMouseClicked
        listDeliveryNoteCtl.searchDeliveryNote(searchDeliveryNoteTF.getText());
    }//GEN-LAST:event_searchDeliveyNoteBtnMouseClicked

    private void searchInvoiceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInvoiceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInvoiceTFActionPerformed
    
     public void showListDeliveryNote(List<DeliveryNote> deliveryNotes){
        DefaultTableModel model = (DefaultTableModel) listDeliveryNote.getModel();

        int rowCount = listDeliveryNote.getRowCount();
        if(rowCount!=0){
            for(int i = rowCount-1;i>=0;i--){
                model.removeRow(i);
            }
        }
        for(int i=0;i<deliveryNotes.size();i++){
            Object[] row = {deliveryNotes.get(i).getInvoiceNumber(),deliveryNotes.get(i).getDeliveryNoteNumber(),
                            deliveryNotes.get(i).getCustomerName(),deliveryNotes.get(i).getOrderDate(),deliveryNotes.get(i).getDeliveryDate(),
                            deliveryNotes.get(i).getStatus()};
            model.addRow(row);
            
            showDeliveryNoteViewButton(deliveryNotes, i);
        }
    }
     
    public void showItemList(List<Item> items) {
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel1.setVisible(true);
        addBtn.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) listItem.getModel();

        int rowCount = listItem.getRowCount();
        if(rowCount!=0){
            for(int i = rowCount-1;i>=0;i--){
                model.removeRow(i);
            }
        }
        for(int i=0;i<items.size();i++){
            Object[] row = {items.get(i).getId(), items.get(i).getTitle(), items.get(i).getManufacturer(), items.get(i).getNumberOfStock()};
            model.addRow(row);
            
            showItemEditButton(items, i);
            
        }
    }
    
    public void showItemEditButton(List<Item> items, int i){
        editButtons = new javax.swing.JButton[items.size()];
        
        editButtons[i] = new javax.swing.JButton("Edit");
        editButtons[i].setSize(60,15);
        editButtons[i].setLocation(0, 16 * i);
        editButtons[i].setName(items.get(i).toString());
        editButtons[i].addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onEditClick(items.get(i), i);
            }
        });
            
        btnHolder.add(editButtons[i]);
    }
    
    public void showDeliveryNoteViewButton(List<DeliveryNote> deliveryNotes, int i){
        dnEditButtons = new javax.swing.JButton[deliveryNotes.size()];
        
        dnEditButtons[i] = new javax.swing.JButton("View");
        dnEditButtons[i].setSize(60,15);
        dnEditButtons[i].setLocation(0, 16 * i);
        dnEditButtons[i].setName(deliveryNotes.get(i).toString());
        dnEditButtons[i].addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onViewClick(deliveryNotes.get(i), i);
            }
        });
            
        dnEditBtnHolder.add(dnEditButtons[i]);
    }
    
    public void onEditClick(Item item, int index){
        itemCtl.requestEditItemForm(item, index);
    }
    
    public void onViewClick(DeliveryNote deliveryNote, int index){
        deliveryNoteCtl.getDeliveryNoteDesciption(deliveryNote, index);
    }
    
    public void onViewClick(Invoice invoice, int index){
        invoiceCtl.getInvoiceDescription(invoice, index);
    }
    
    public void showListInvoice(List<Invoice> invoices) {
        jPanel1.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true); 
        
        DefaultTableModel model = (DefaultTableModel) listInvoice.getModel();

        int rowCount = listInvoice.getRowCount();
        if(rowCount!=0){
            for(int i = rowCount-1;i>=0;i--){
                model.removeRow(i);
            }
        }
        for(int i=0;i<invoices.size();i++){
            Object[] row = {invoices.get(i).getInvoiceNumber(),invoices.get(i).getPONumber(),
                            invoices.get(i).getSupplierName(),invoices.get(i).getOrderDate(),invoices.get(i).getDeliveryDate(),
                            invoices.get(i).getStatus()};
            model.addRow(row);
            
            showInvoiceViewButton(invoices, i);
        }
    }
    
     public void showInvoiceViewButton(List<Invoice> invoices, int i){
        invoiceViewBtns = new javax.swing.JButton[invoices.size()];
        
        invoiceViewBtns[i] = new javax.swing.JButton("View");
        invoiceViewBtns[i].setSize(60,15);
        invoiceViewBtns[i].setLocation(0, 16 * i);
        invoiceViewBtns[i].setName(invoices.get(i).toString());
        invoiceViewBtns[i].addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onViewClick(invoices.get(i), i);
            }
        });
            
        invoiceViewBtnHolder.add(invoiceViewBtns[i]);
    }
     
    public void refreshItemList(){
        listItemCtl.getItemList();
        //refresh data on table
    }
    
    public void refreshDeliveryNoteList(){
        listDeliveryNoteCtl.getListDeliveryNote();
    }
    
    public void refreshInvoiceList(){
        listInvoiceCtl.getListInvoice();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainPage().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }); 
        
    }
    
    
    
    
    private javax.swing.JButton[] invoiceViewBtns;
    private javax.swing.JButton[] dnEditButtons;
    private javax.swing.JButton[] editButtons;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel btnHolder;
    private javax.swing.JMenu createDeliveryNoteMenu;
    private javax.swing.JMenu deliveryNotesMI;
    private javax.swing.JPanel dnEditBtnHolder;
    private javax.swing.JMenu invoiceMI;
    private javax.swing.JPanel invoiceViewBtnHolder;
    private javax.swing.JMenu itemMI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listDeliveryNote;
    private javax.swing.JTable listInvoice;
    private javax.swing.JTable listItem;
    private javax.swing.JMenuBar menuMB;
    private javax.swing.JTextField searchDeliveryNoteTF;
    private javax.swing.JButton searchDeliveyNoteBtn;
    private javax.swing.JButton searchInvoiceBtn;
    private javax.swing.JTextField searchInvoiceTF;
    private javax.swing.JButton searchItemBtn;
    private javax.swing.JTextField searchItemTF;
    private javax.swing.JButton viewDeliveryNoteBtn;
    private javax.swing.JMenu viewDeliveryNoteMenu;
    // End of variables declaration//GEN-END:variables
}
